# https://woodpecker-ci.org/docs/usage/intro
pipeline:
  build_and_test:
    image: rust
    commands:
      - cargo build --release
      - cargo test --release

  notify:
    # http://plugins.drone.io/appleboy/drone-discord/
    image: appleboy/drone-discord
    commands:
      - echo $DISCORD_ID
      - echo $DISCORD_TOKEN
      - echo $discord_id
      - echo $discord_token
    settings:
      webhook_id: $DISCORD_ID
        #from_secret: discord_id
      webhook_token: $DISCORD_TOKEN
        #from_secret: discord_token
      message: >
        {{#success build.status}}
          build {{build.number}} succeeded. Good job.
        {{else}}
          build {{build.number}} failed. Fix me please.
        {{/success}}
