# https://woodpecker-ci.org/docs/usage/intro
pipeline:
  build_and_test:
    image: rust
    commands:
      - cargo build --release
      - cargo test --release

  notify:
    # http://plugins.drone.io/appleboy/drone-discord/
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: discord_id
      webhook_token:
        from_secret: discord_token
      message: >
        {{#success build.status}}
          build {{build.number}} succeeded. Good job.
        {{else}}
          build {{build.number}} failed. Fix me please.
        {{/success}}
